/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_nix_jpcap_JpcapSender */

#ifndef _Included_com_nix_jpcap_JpcapSender
#define _Included_com_nix_jpcap_JpcapSender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nix_jpcap_JpcapSender
 * Method:    nativeOpenDevice
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nix_jpcap_JpcapSender_nativeOpenDevice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_nix_jpcap_JpcapSender
 * Method:    nativeSendPacket
 * Signature: (Ljpcap/packet/TCPPacket;)V
 */
JNIEXPORT void JNICALL Java_com_nix_jpcap_JpcapSender_nativeSendPacket
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
