/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_nix_jpcap_JpcapCaptor */

#ifndef _Included_com_nix_jpcap_JpcapCaptor
#define _Included_com_nix_jpcap_JpcapCaptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nix_jpcap_JpcapCaptor
 * Method:    getDeviceList
 * Signature: ()[Lcom/nix/jpcap/NetworkInterface;
 */
JNIEXPORT jobjectArray JNICALL Java_com_nix_jpcap_JpcapCaptor_getDeviceList
  (JNIEnv *, jclass);

/*
 * Class:     com_nix_jpcap_JpcapCaptor
 * Method:    setPacketReadTimeout
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nix_jpcap_JpcapCaptor_setPacketReadTimeout
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_nix_jpcap_JpcapCaptor
 * Method:    loopPacket
 * Signature: (ILcom/nix/jpcap/PacketReceiver;)I
 */
JNIEXPORT jint JNICALL Java_com_nix_jpcap_JpcapCaptor_loopPacket
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_nix_jpcap_JpcapCaptor
 * Method:    nativeOpenLive
 * Signature: (Ljava/lang/String;III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nix_jpcap_JpcapCaptor_nativeOpenLive
  (JNIEnv *, jobject, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
